select * from customer limit 20

-- Q1. What is the total revenue generated by male vs. female customers?
select gender , SUM(purchase_amount) as revenue
from customer
group by gender

-- Q2. Which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

-- Q3. Which are top 5 highest products with the average rating?
select item_purchased ,ROUND(AVG(review_rating::numeric),2) AS "Average Product Rating"
from customer 
group by item_purchased
order by avg(review_rating) DESC 
limit 5;

-- Q4. Compare the AVG amount between standart and express shipping
select shipping_type,
round(AVG (purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

-- Q5. Do subscribed customers spend more? compare avg and total revenue btw sub and non-sub
select subscription_status ,
count (customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) AS avg_spend,
ROUND(COUNT(purchase_amount),2) AS tota_revenue
from customer
group by subscription_status
order by tota_revenue , avg_spend desc;

-- Q6. Which 5 projcts have the highest percentage of purchases with the discount applyed?
select item_purchased ,
ROUND (100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer
GROUP BY item_purchased
ORDER BY discount_rate DESC 
LIMIT 5

-- Q7. Segment customers into New, Returning, and Loyal based on
-- their total number of previous purchases, and show count of each segment.
WITH customer_type AS (
  SELECT 
    customer_id,
    previous_purchases,
    CASE
      WHEN previous_purchases = 1 THEN 'New'
      WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
      ELSE 'Loyal'
    END AS customer_segment
  FROM customer
)
SELECT 
  customer_segment,
  COUNT(*) AS "Number Of Customers"
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products within each category?
with item_count as (
select category , 
item_purchased,
count(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id)DESC)as item_rank
from customer
group by category , item_purchased
)
select item_rank, category,item_purchased,total_orders
from item_count
where item_rank <= 3;

-- Q9. Are customer who are repeat buyers (more than 5 previous purchase) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

-- Q10. What is the revenue contrituion of each age group?
select age_group,sum(purchase_amount) as Revenue
from customer
group by age_group
order by Revenue desc;